/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

const val TermA: Double = 6.00
const val TermB: Double = 2.00
const val TermC: Double = 3.00

fun main() {
    
    if (TermA == 0.0) {
        println("El término A es 0.")
    } else {
        println("El término A no es 0.")
    }

    for (i in -5..5) {
        val x = i.toDouble()
        println("x = $x")
        println("f(x) = ${calcularF(TermA, TermB, TermC, x)}")
    }
    println("${TermA}x² + ${TermB}x + ${TermC}")
}

fun calcularF(TermA: Double, TermB: Double, TermC: Double, x: Double): Double {
    return TermA * x * x + TermB * x + TermC
}


